<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>CDPlayer.Windows</RootNamespace>
    <AssemblyName>CDPlayer.Windows</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

</Project>
