'use strict';
// The renderer's only door to the system: a small, explicit API (no Node access in the page itself).
const { contextBridge, ipcRenderer, webUtils } = require('electron');

const invoke = (channel) => (...args) => ipcRenderer.invoke(channel, ...args);
const on = (channel) => (callback) => ipcRenderer.on(channel, (_e, ...args) => callback(...args));

contextBridge.exposeInMainWorld('cdp', {
  loadState: invoke('state:load'),
  saveSettings: invoke('state:saveSettings'),
  saveQueue: invoke('state:saveQueue'),
  saveQueueSync: (q) => ipcRenderer.sendSync('state:saveQueueSync', q),
  i18nDict: () => ipcRenderer.sendSync('i18n:dict'),
  listLanguages: invoke('i18n:list'),
  relaunch: invoke('app:relaunch'),
  saveHistory: invoke('state:saveHistory'),
  saveEqPresets: invoke('state:saveEqPresets'),
  markOnboarded: invoke('state:markOnboarded'),
  outputRate: {
    list: invoke('outputRate:list'),
    current: invoke('outputRate:current'),
    set: invoke('outputRate:set'),
    restore: invoke('outputRate:restore'),
  },
  writeLastVersion: invoke('state:writeLastVersion'),

  exists: invoke('fs:exists'),
  details: invoke('meta:details'),
  addPlay: invoke('plays:add'),
  playCount: invoke('plays:count'),
  playTimes: invoke('plays:times'),
  albumPlays: invoke('plays:album'),
  wipeAlbum: invoke('dust:wipe'),
  setNote: invoke('notes:set'),
  shelfColors: invoke('shelf:colors'),
  saveShelfColors: invoke('shelf:saveColors'),
  tearWrap: invoke('wrap:tear'),
  wantDiscography: invoke('discography:want'),
  missingTracklist: invoke('discography:tracklist'),
  discogsLookup: invoke('discogs:lookup'),
  discogsAppraise: invoke('discogs:appraise'),
  discogsStop: invoke('discogs:stop'),
  discogsVersions: invoke('discogs:versions'),
  discogsSearch: invoke('discogs:search'),
  discogsChoose: invoke('discogs:choose'),
  discogsKnown: invoke('discogs:known'),
  discogsNotFound: invoke('discogs:notFound'),
  discogsSettings: invoke('discogs:settings'),
  discogsSetToken: invoke('discogs:setToken'),
  discogsSetCurrency: invoke('discogs:setCurrency'),
  openDiscogs: invoke('discogs:open'),
  onDiscogsProgress: on('discogs-progress'),
  hideMissing: invoke('discography:hide'),
  openMusicBrainz: invoke('discography:open'),
  onDiscography: on('discography'),
  dockDisc: invoke('dock:disc'),
  setTaskbarDisc: invoke('dock:taskbarDisc'),
  copyImage: invoke('clipboard:image'),
  saveCard: invoke('dialog:saveCard'),
  saveVideo: invoke('dialog:saveVideo'),
  discMenu: invoke('menu:disc'),
  findCover: invoke('online:cover'),
  findCoverUrl: invoke('online:coverUrl'),
  findLyrics: invoke('online:lyrics'),
  readTags: invoke('tags:read'),
  lookupTags: invoke('tags:lookup'),
  coverFromUrl: invoke('tags:coverFromUrl'),
  writeTags: invoke('tags:write'),
  classifySpotifyLink: invoke('spotify:classify'),
  resolveSpotifyLink: invoke('spotify:resolve'),
  spotifySignIn: invoke('spotify:signIn'),
  spotifyCheckKeys: invoke('spotify:checkKeys'),
  spotifyVerify: invoke('spotify:verify'),
  spotifyDiagnose: invoke('spotify:diagnose'),
  clipboardText: invoke('clipboard:text'),
  spotifyStatus: invoke('spotify:status'),
  disconnectSpotify: invoke('spotify:disconnect'),
  saveSpotifyCredentials: invoke('spotify:saveCredentials'),
  spotifyAccessToken: invoke('spotify:accessToken'),
  spotifyAlbums: invoke('spotify:albums'),
  spotifyPlaylists: invoke('spotify:playlists'),
  spotifySearch: invoke('spotify:search'),
  spotifyDiscTracks: invoke('spotify:discTracks'),
  spotifyPlay: invoke('spotify:play'),
  spotifyCover: invoke('spotify:cover'),
  spotifyDrmReady: invoke('spotify:drmReady'),
  spotifyLog: invoke('spotify:log'),
  showSpotifyLog: invoke('spotify:showLog'),
  openSpotifyDashboard: invoke('spotify:openDashboard'),

  collectAudio: invoke('library:collect'),
  scanLibrary: invoke('library:scan'),
  shelfAlbums: invoke('shelf:albums'),
  shelfCover: invoke('shelf:cover'),
  shelfCoverFull: invoke('shelf:coverFull'),
  onShelfProgress: on('shelf-progress'),
  checkLibrary: invoke('library:check'),
  onLibraryCheck: on('library-check'),
  showFile: invoke('shell:showFile'),
  pickMusicFolder: invoke('dialog:pickMusicFolder'),
  listAudioCds: invoke('cd:list'),
  ejectAudioCd: invoke('cd:eject'),
  startRip: invoke('rip:start'),
  cancelRip: invoke('rip:cancel'),
  showRipFolder: invoke('rip:showFolder'),
  onRipProgress: on('rip-progress'),
  onAudioCd: on('audio-cd'),
  onAudioCdGone: on('audio-cd-gone'),
  openTracksDialog: invoke('dialog:openTracks'),
  savePlaylistDialog: invoke('dialog:savePlaylist'),
  loadPlaylistDialog: invoke('dialog:loadPlaylist'),
  importLibraryDialog: invoke('dialog:importLibrary'),

  setMiniMode: invoke('win:setMiniMode'),
  toggleFullscreen: invoke('win:toggleFullscreen'),
  isFullscreen: invoke('win:isFullscreen'),
  openGitHub: invoke('shell:openGitHub'),
  copyText: invoke('clipboard:write'),
  themes: {
    list: invoke('themes:list'), save: invoke('themes:save'), remove: invoke('themes:delete'),
    importFile: invoke('themes:import'), exportFile: invoke('themes:export'),
    encode: invoke('themes:encode'), decode: invoke('themes:decode'),
  },
  checkForUpdate: invoke('updates:check'),
  openReleasesPage: invoke('updates:openReleases'),
  downloadUpdate: invoke('updates:download'),
  installUpdate: invoke('updates:install'),
  onUpdateProgress: on('update-progress'),
  setDiscordTrack: (track) => ipcRenderer.send('discord:track', track),

  pathForFile: (file) => webUtils.getPathForFile(file),
  mediaUrl: (p) => `cdp://app/media?p=${encodeURIComponent(p)}`,

  onOpenFiles: on('open-files'),
  onFullscreenChanged: on('fullscreen-changed'),
  onAppClosing: on('app-closing'),

  // Mini player <-> main window
  sendMiniState: (state) => ipcRenderer.send('mini:state', state),
  onMiniState: on('mini-state'),
  sendMiniCommand: (command) => ipcRenderer.send('mini:command', command),
  onMiniCommand: on('mini-command'),
});
