'use strict';
// The renderer's only door to the system: a small, explicit API (no Node access in the page itself).
const { contextBridge, ipcRenderer, webUtils } = require('electron');

const invoke = (channel) => (...args) => ipcRenderer.invoke(channel, ...args);
const on = (channel) => (callback) => ipcRenderer.on(channel, (_e, ...args) => callback(...args));

contextBridge.exposeInMainWorld('cdp', {
  loadState: invoke('state:load'),
  saveSettings: invoke('state:saveSettings'),
  saveQueue: invoke('state:saveQueue'),
  saveQueueSync: (q) => ipcRenderer.sendSync('state:saveQueueSync', q),
  saveHistory: invoke('state:saveHistory'),
  saveEqPresets: invoke('state:saveEqPresets'),
  markOnboarded: invoke('state:markOnboarded'),
  writeLastVersion: invoke('state:writeLastVersion'),

  exists: invoke('fs:exists'),
  details: invoke('meta:details'),
  addPlay: invoke('plays:add'),
  playCount: invoke('plays:count'),
  playTimes: invoke('plays:times'),
  albumPlays: invoke('plays:album'),
  wipeAlbum: invoke('dust:wipe'),
  setNote: invoke('notes:set'),
  tearWrap: invoke('wrap:tear'),
  wantDiscography: invoke('discography:want'),
  missingTracklist: invoke('discography:tracklist'),
  hideMissing: invoke('discography:hide'),
  openMusicBrainz: invoke('discography:open'),
  onDiscography: on('discography'),
  dockDisc: invoke('dock:disc'),
  copyImage: invoke('clipboard:image'),
  saveCard: invoke('dialog:saveCard'),
  discMenu: invoke('menu:disc'),
  findCover: invoke('online:cover'),
  findCoverUrl: invoke('online:coverUrl'),
  findLyrics: invoke('online:lyrics'),
  readTags: invoke('tags:read'),
  lookupTags: invoke('tags:lookup'),
  coverFromUrl: invoke('tags:coverFromUrl'),
  writeTags: invoke('tags:write'),
  classifySpotifyLink: invoke('spotify:classify'),
  resolveSpotifyLink: invoke('spotify:resolve'),
  spotifySignIn: invoke('spotify:signIn'),
  spotifyStatus: invoke('spotify:status'),
  disconnectSpotify: invoke('spotify:disconnect'),
  saveSpotifyCredentials: invoke('spotify:saveCredentials'),
  spotifyAccessToken: invoke('spotify:accessToken'),
  spotifyAlbums: invoke('spotify:albums'),
  spotifyPlaylists: invoke('spotify:playlists'),
  spotifySearch: invoke('spotify:search'),
  spotifyDiscTracks: invoke('spotify:discTracks'),
  spotifyPlay: invoke('spotify:play'),
  spotifyCover: invoke('spotify:cover'),
  spotifyDrmReady: invoke('spotify:drmReady'),
  spotifyLog: invoke('spotify:log'),
  showSpotifyLog: invoke('spotify:showLog'),
  openSpotifyDashboard: invoke('spotify:openDashboard'),

  collectAudio: invoke('library:collect'),
  scanLibrary: invoke('library:scan'),
  shelfAlbums: invoke('shelf:albums'),
  shelfCover: invoke('shelf:cover'),
  shelfCoverFull: invoke('shelf:coverFull'),
  onShelfProgress: on('shelf-progress'),
  pickMusicFolder: invoke('dialog:pickMusicFolder'),
  listAudioCds: invoke('cd:list'),
  ejectAudioCd: invoke('cd:eject'),
  startRip: invoke('rip:start'),
  cancelRip: invoke('rip:cancel'),
  showRipFolder: invoke('rip:showFolder'),
  onRipProgress: on('rip-progress'),
  onAudioCd: on('audio-cd'),
  onAudioCdGone: on('audio-cd-gone'),
  openTracksDialog: invoke('dialog:openTracks'),
  savePlaylistDialog: invoke('dialog:savePlaylist'),
  loadPlaylistDialog: invoke('dialog:loadPlaylist'),
  importLibraryDialog: invoke('dialog:importLibrary'),

  setMiniMode: invoke('win:setMiniMode'),
  toggleFullscreen: invoke('win:toggleFullscreen'),
  isFullscreen: invoke('win:isFullscreen'),
  openGitHub: invoke('shell:openGitHub'),
  copyText: invoke('clipboard:write'),
  checkForUpdate: invoke('updates:check'),
  openReleasesPage: invoke('updates:openReleases'),
  setDiscordTrack: (track) => ipcRenderer.send('discord:track', track),

  pathForFile: (file) => webUtils.getPathForFile(file),
  mediaUrl: (p) => `cdp://app/media?p=${encodeURIComponent(p)}`,

  onOpenFiles: on('open-files'),
  onFullscreenChanged: on('fullscreen-changed'),
  onAppClosing: on('app-closing'),

  // Mini player <-> main window
  sendMiniState: (state) => ipcRenderer.send('mini:state', state),
  onMiniState: on('mini-state'),
  sendMiniCommand: (command) => ipcRenderer.send('mini:command', command),
  onMiniCommand: on('mini-command'),
});
